// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.14.0
// source: wiki.proto

package puzzlewikiservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WikiClient is the client API for Wiki service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WikiClient interface {
	Load(ctx context.Context, in *WikiRequest, opts ...grpc.CallOption) (*Content, error)
	Store(ctx context.Context, in *ContentRequest, opts ...grpc.CallOption) (*Response, error)
	ListVersions(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*Versions, error)
	Delete(ctx context.Context, in *WikiRequest, opts ...grpc.CallOption) (*Response, error)
}

type wikiClient struct {
	cc grpc.ClientConnInterface
}

func NewWikiClient(cc grpc.ClientConnInterface) WikiClient {
	return &wikiClient{cc}
}

func (c *wikiClient) Load(ctx context.Context, in *WikiRequest, opts ...grpc.CallOption) (*Content, error) {
	out := new(Content)
	err := c.cc.Invoke(ctx, "/puzzlewikiservice.Wiki/Load", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wikiClient) Store(ctx context.Context, in *ContentRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/puzzlewikiservice.Wiki/Store", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wikiClient) ListVersions(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*Versions, error) {
	out := new(Versions)
	err := c.cc.Invoke(ctx, "/puzzlewikiservice.Wiki/ListVersions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wikiClient) Delete(ctx context.Context, in *WikiRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/puzzlewikiservice.Wiki/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WikiServer is the server API for Wiki service.
// All implementations must embed UnimplementedWikiServer
// for forward compatibility
type WikiServer interface {
	Load(context.Context, *WikiRequest) (*Content, error)
	Store(context.Context, *ContentRequest) (*Response, error)
	ListVersions(context.Context, *VersionRequest) (*Versions, error)
	Delete(context.Context, *WikiRequest) (*Response, error)
	mustEmbedUnimplementedWikiServer()
}

// UnimplementedWikiServer must be embedded to have forward compatible implementations.
type UnimplementedWikiServer struct {
}

func (UnimplementedWikiServer) Load(context.Context, *WikiRequest) (*Content, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Load not implemented")
}
func (UnimplementedWikiServer) Store(context.Context, *ContentRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Store not implemented")
}
func (UnimplementedWikiServer) ListVersions(context.Context, *VersionRequest) (*Versions, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVersions not implemented")
}
func (UnimplementedWikiServer) Delete(context.Context, *WikiRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedWikiServer) mustEmbedUnimplementedWikiServer() {}

// UnsafeWikiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WikiServer will
// result in compilation errors.
type UnsafeWikiServer interface {
	mustEmbedUnimplementedWikiServer()
}

func RegisterWikiServer(s grpc.ServiceRegistrar, srv WikiServer) {
	s.RegisterService(&Wiki_ServiceDesc, srv)
}

func _Wiki_Load_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WikiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WikiServer).Load(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/puzzlewikiservice.Wiki/Load",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WikiServer).Load(ctx, req.(*WikiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wiki_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WikiServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/puzzlewikiservice.Wiki/Store",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WikiServer).Store(ctx, req.(*ContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wiki_ListVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WikiServer).ListVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/puzzlewikiservice.Wiki/ListVersions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WikiServer).ListVersions(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wiki_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WikiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WikiServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/puzzlewikiservice.Wiki/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WikiServer).Delete(ctx, req.(*WikiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Wiki_ServiceDesc is the grpc.ServiceDesc for Wiki service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Wiki_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "puzzlewikiservice.Wiki",
	HandlerType: (*WikiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Load",
			Handler:    _Wiki_Load_Handler,
		},
		{
			MethodName: "Store",
			Handler:    _Wiki_Store_Handler,
		},
		{
			MethodName: "ListVersions",
			Handler:    _Wiki_ListVersions_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Wiki_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wiki.proto",
}
